name: check

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up system
        shell: bash
        run: |
          sudo apt-get update -qq
          sudo apt-get install git-annex
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox datalad
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.HYPOTHESIS_EXAMPLE_DB_REPO_KEY }}
      - name: Fetch hypothesis example database
        run: |
          git clone git@github.com:matrss/datalad-getexec-hypothesis-example-db.git .hypothesis
          git -C .hypothesis config annex.private true
          git -C .hypothesis annex init
          datalad get -d .hypothesis
      - name: Run tox test suite
        run: |
          tox -- --hypothesis-show-statistics --hypothesis-profile ci
      - name: Save and push hypothesis example database
        if: ${{ always() && matrix.python-version == '3.11' }}
        run: |
          datalad save -d .hypothesis
          datalad push -d .hypothesis --to origin
